export { default as cloud } from '../assets/images/cloud.svg'
export { default as davlenie } from '../assets/images/davlenie.svg'
export { default as headerBg } from '../assets/images/headerBg.svg'
export { default as kaplya } from '../assets/images/kaplya.svg'
export { default as logo } from '../assets/images/logo.svg'
export { default as minicloud } from '../assets/images/minicloud.svg'
export { default as minirain } from '../assets/images/minirain.svg'
export { default as osadki } from '../assets/images/osadki.svg'
export { default as rain } from '../assets/images/rain.svg'
export { default as sun } from '../assets/images/sun.svg'
export { default as sunrain } from '../assets/images/sunrain.svg'
export { default as temp } from '../assets/images/temp.svg'
export { default as water } from '../assets/images/water.svg'
export { default as wind } from '../assets/images/wind.svg'


